# Capstone 2 - Lending Club Loan Defaults Prediction
Sudha Kumar
7/13/2020

Data URL - https://www.kaggle.com/wendykan/lending-club-loan-data

## Data Wrangling
Data wrangling is the second step in the Data Science Method. This step consists of multiple components including Data Collection, Data Organization, Data Definitions, and Data Cleaning.

In [1]:
#load python packages
import os
import pandas as pd
import pandas.api.types as ptypes
import datetime
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

### Data Collection 
Read data from "loan.csv" file.

In [40]:
df = pd.read_csv("loan.csv")
df.head(5)

C:\Users\Umesh\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (19,47,55,112,123,124,125,128,129,130,133,139,140,141) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


id  member_id  loan_amnt  funded_amnt  funded_amnt_inv        term  \
0 NaN        NaN       2500         2500           2500.0   36 months   
1 NaN        NaN      30000        30000          30000.0   60 months   
2 NaN        NaN       5000         5000           5000.0   36 months   
3 NaN        NaN       4000         4000           4000.0   36 months   
4 NaN        NaN      30000        30000          30000.0   60 months   

   int_rate  installment grade sub_grade  ... hardship_payoff_balance_amount  \
0     13.56        84.92     C        C1  ...                            NaN   
1     18.94       777.23     D        D2  ...                            NaN   
2     17.97       180.69     D        D1  ...                            NaN   
3     18.94       146.51     D        D2  ...                            NaN   
4     16.14       731.78     C        C4  ...                            NaN   

  hardship_last_payment_amount disbursement_method  debt_settlement_flag  \
0                          NaN                Cash                     N   
1                          NaN                Cash                     N   
2                          NaN                Cash                     N   
3                          NaN                Cash                     N   
4                          NaN                Cash                     N   

  debt_settlement_flag_date settlement_status settlement_date  \
0                       NaN               NaN             NaN   
1                       NaN               NaN             NaN   
2                       NaN               NaN             NaN   
3                       NaN               NaN             NaN   
4                       NaN               NaN             NaN   

  settlement_amount  settlement_percentage settlement_term  
0               NaN                    NaN             NaN  
1               NaN                    NaN             NaN  
2               NaN                    NaN             NaN  
3               NaN                    NaN             NaN  
4               NaN                    NaN             NaN  

[5 rows x 145 columns]

#### Handle mixed data types in Columns (19,47,55,112,123,124,125,128,129,130,133,139,140,141)

In [41]:
col_names = df.columns
col_names

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       ...
       'hardship_payoff_balance_amount', 'hardship_last_payment_amount',
       'disbursement_method', 'debt_settlement_flag',
       'debt_settlement_flag_date', 'settlement_status', 'settlement_date',
       'settlement_amount', 'settlement_percentage', 'settlement_term'],
      dtype='object', length=145)

In [42]:
col_names[19]

'desc'

In [43]:
df['desc'].unique()

array([nan, ' ',
       "I currently have a loan out with CashCall. The interest rate is 96%! At the time I took out the loan, it helped with a family crisis, but now the interest is crazy to be paying. I'd rather be paying my $200 a month to pay down a loan rather than just the interest.   Also, the remainder of my debt has interest rates ranging from 20 - 24%. This includes credit cards, a student loan, and some personal loans. So, I would like to consolidate the rest of my debt and pay a lower interest rate of 15%.  By doing this, I could lower my interest and my monthly payments and save at least $4000 over the next few years.  I do have a bankruptcy that was discharged 3 years ago due to having $40,000 in debt from an uninsured hospital stay. However, I've not missed a payment on anything since.  My credit report does from time time to time relist things as collections and then I have to dispute them as included in bankruptcy and they go back to being listed that way. I'm not sure

In [44]:
col_names[47]

'next_pymnt_d'

In [45]:
df['next_pymnt_d'].unique()

array(['Mar-2019', nan, 'Feb-2019', 'Apr-2019', 'Dec-2018', 'Sep-2018',
       'Aug-2018', 'Feb-2018', 'Jan-2016', 'Sep-2013', 'Feb-2016',
       'Feb-2014', 'May-2014', 'Jun-2013', 'Mar-2012', 'Apr-2012',
       'May-2013', 'Aug-2012', 'Aug-2013', 'Jun-2012', 'Nov-2013',
       'Feb-2012', 'Oct-2011', 'Jan-2013', 'Jan-2014', 'Jul-2013',
       'Jul-2015', 'Jan-2012', 'Dec-2012', 'Jun-2011', 'Feb-2013',
       'Nov-2011', 'Nov-2012', 'Dec-2011', 'Aug-2011', 'Sep-2011',
       'Apr-2011', 'Mar-2014', 'Apr-2013', 'Mar-2011', 'Jul-2012',
       'Aug-2014', 'Oct-2013', 'Sep-2012', 'May-2012', 'Apr-2015',
       'Jul-2011', 'Dec-2015', 'Dec-2013', 'Jan-2011', 'Oct-2012',
       'Nov-2014', 'Mar-2013', 'Aug-2015', 'Feb-2015', 'May-2015',
       'Jul-2014', 'Nov-2015', 'Sep-2014', 'Oct-2015', 'May-2011',
       'Feb-2011', 'Dec-2014', 'Jun-2015', 'Apr-2014', 'Jan-2015',
       'Sep-2015', 'Jun-2014', 'Nov-2010', 'Oct-2010', 'Dec-2010',
       'Mar-2015', 'Oct-2014', 'Jul-2010', 'Sep-2010', 'M

In [46]:
col_names[55]

'verification_status_joint'

In [47]:
df['verification_status_joint'].unique()

array([nan, 'Verified', 'Not Verified', 'Source Verified'], dtype=object)

In [48]:
col_names[112]

'sec_app_earliest_cr_line'

In [49]:
df['sec_app_earliest_cr_line'].unique()

array([nan, 'May-2002', 'Aug-2003', 'May-2003', 'Oct-1999', 'Dec-1996',
       'May-2007', 'Oct-2006', 'Nov-1996', 'Jul-1997', 'Apr-1990',
       'Jul-2006', 'Jan-2005', 'Jan-2008', 'Jun-2003', 'Apr-2003',
       'Mar-2008', 'Sep-2005', 'Nov-2001', 'Nov-2006', 'Jan-2016',
       'Aug-1998', 'Sep-2004', 'Mar-2005', 'Jun-2002', 'Jan-2009',
       'Jun-2013', 'Feb-1999', 'Sep-1985', 'Oct-1993', 'Oct-2004',
       'Jun-2004', 'Feb-2004', 'Apr-2000', 'May-2006', 'Aug-1989',
       'Sep-2011', 'Nov-2002', 'Feb-2015', 'Aug-1972', 'Jul-2008',
       'Feb-1985', 'Feb-2008', 'Sep-2002', 'Jul-1998', 'Jan-1988',
       'Dec-2005', 'Jun-1988', 'Feb-2009', 'May-2000', 'Feb-1992',
       'Oct-1996', 'Sep-2006', 'Nov-2010', 'Nov-2003', 'Jun-2006',
       'May-2011', 'Nov-1988', 'Jul-1991', 'Apr-1991', 'Dec-1998',
       'Aug-2010', 'Mar-2007', 'Feb-2007', 'Nov-2008', 'Mar-2009',
       'Mar-1997', 'Oct-2009', 'Oct-2007', 'Jan-1999', 'Dec-2002',
       'Aug-2005', 'Jul-2010', 'Jul-2001', 'Sep-2016', 'J

In [50]:
col_names[123]

'hardship_type'

In [51]:
df['hardship_type'].unique()

array([nan, 'INTEREST ONLY-3 MONTHS DEFERRAL'], dtype=object)

In [52]:
col_names[124]

'hardship_reason'

In [53]:
df['hardship_reason'].unique()

array([nan, 'UNEMPLOYMENT', 'NATURAL_DISASTER', 'EXCESSIVE_OBLIGATIONS',
       'MEDICAL', 'INCOME_CURTAILMENT', 'DISABILITY', 'REDUCED_HOURS',
       'FAMILY_DEATH', 'DIVORCE'], dtype=object)

In [54]:
col_names[125]

'hardship_status'

In [55]:
df['hardship_status'].unique()

array([nan, 'ACTIVE', 'COMPLETED', 'BROKEN'], dtype=object)

In [56]:
col_names[128]

'hardship_start_date'

In [57]:
df['hardship_start_date'].unique()

array([nan, 'Feb-2019', 'Oct-2018', 'Nov-2018', 'Sep-2018', 'Jan-2019',
       'Dec-2018', 'Aug-2018', 'Jul-2018', 'May-2018', 'Sep-2017',
       'Feb-2018', 'Dec-2017', 'Apr-2018', 'Aug-2017', 'Jan-2018',
       'Mar-2018', 'Jun-2018', 'Oct-2017', 'Nov-2017', 'Jul-2017',
       'Jun-2017', 'May-2017', 'Feb-2017', 'Apr-2017', 'Jan-2017',
       'Mar-2017'], dtype=object)

In [58]:
col_names[129]

'hardship_end_date'

In [59]:
df['hardship_end_date'].unique()

array([nan, 'Apr-2019', 'Dec-2018', 'Jan-2019', 'Feb-2019', 'Oct-2018',
       'May-2019', 'Mar-2019', 'Nov-2018', 'Aug-2018', 'Dec-2017',
       'May-2018', 'Nov-2017', 'Mar-2018', 'Jul-2018', 'Apr-2018',
       'Jun-2018', 'Sep-2017', 'Sep-2018', 'Oct-2017', 'Jan-2018',
       'Feb-2018', 'Aug-2017', 'Jul-2017', 'Jun-2017', 'May-2017',
       'Apr-2017', 'Mar-2017'], dtype=object)

In [60]:
col_names[130]

'payment_plan_start_date'

In [61]:
df['payment_plan_start_date'].unique()

array([nan, 'Feb-2019', 'Oct-2018', 'Nov-2018', 'Dec-2018', 'Jan-2019',
       'Sep-2018', 'Mar-2019', 'Aug-2018', 'Jun-2018', 'Sep-2017',
       'Oct-2017', 'Feb-2018', 'Dec-2017', 'May-2018', 'Aug-2017',
       'Jan-2018', 'Mar-2018', 'Apr-2018', 'Nov-2017', 'Jul-2018',
       'Jul-2017', 'Jun-2017', 'May-2017', 'Mar-2017', 'Feb-2017',
       'Apr-2017'], dtype=object)

In [62]:
col_names[133]

'hardship_loan_status'

In [63]:
df['hardship_loan_status'].unique()

array([nan, 'Late (16-30 days)', 'Issued', 'Current',
       'Late (31-120 days)', 'In Grace Period'], dtype=object)

In [64]:
col_names[139]

'debt_settlement_flag_date'

In [65]:
df['debt_settlement_flag_date'].unique()

array([nan, 'Feb-2019', 'Dec-2018', 'Jan-2019', 'Nov-2018', 'Oct-2018',
       'Sep-2018', 'Aug-2018', 'Jul-2018', 'Jun-2018', 'Apr-2018',
       'Dec-2017', 'Feb-2018', 'Sep-2017', 'May-2018', 'Mar-2018',
       'Nov-2017', 'Jan-2018', 'Jun-2017', 'May-2017', 'Jul-2017',
       'Aug-2017', 'Oct-2017', 'Apr-2017', 'Mar-2017', 'Jan-2017',
       'Feb-2017', 'Dec-2016', 'Nov-2016', 'Aug-2016', 'Sep-2016',
       'Jul-2016', 'Oct-2016', 'Jun-2016', 'May-2016', 'Apr-2016',
       'Mar-2016', 'Feb-2016', 'Jan-2016', 'Dec-2015', 'Sep-2015',
       'Oct-2015', 'Aug-2015', 'Jun-2015', 'Feb-2015', 'Nov-2015',
       'May-2015', 'Nov-2014', 'Mar-2015', 'Apr-2015', 'Jul-2015',
       'Jan-2015', 'Dec-2014', 'May-2014', 'Sep-2014', 'Jul-2014',
       'Apr-2014', 'Jun-2014', 'Oct-2014', 'Aug-2014', 'Aug-2013',
       'Mar-2014', 'Jan-2014', 'Nov-2013', 'Oct-2013', 'Feb-2014',
       'Sep-2013', 'Mar-2013', 'Jun-2013', 'Nov-2012', 'Dec-2013',
       'Oct-2012', 'Jun-2012', 'Apr-2013', 'Jul-2013', 'F

In [66]:
col_names[140]

'settlement_status'

In [67]:
df['settlement_status'].unique()

array([nan, 'ACTIVE', 'COMPLETE', 'BROKEN'], dtype=object)

In [68]:
col_names[141]

'settlement_date'

In [69]:
df['settlement_date'].unique()

array([nan, 'Feb-2019', 'Dec-2018', 'Jan-2019', 'Nov-2018', 'Oct-2018',
       'Sep-2018', 'Aug-2018', 'Jul-2018', 'Jun-2018', 'Apr-2018',
       'Aug-2017', 'Nov-2017', 'Jan-2018', 'Jun-2017', 'May-2018',
       'Jul-2017', 'Feb-2018', 'Mar-2018', 'Dec-2017', 'May-2017',
       'Sep-2017', 'Oct-2017', 'Feb-2017', 'Jan-2017', 'Mar-2017',
       'Apr-2017', 'Dec-2016', 'Nov-2016', 'Oct-2016', 'Sep-2016',
       'Aug-2016', 'Jul-2016', 'Jun-2016', 'Apr-2016', 'May-2016',
       'Mar-2016', 'Feb-2016', 'Jan-2016', 'Dec-2015', 'Oct-2015',
       'Sep-2015', 'Aug-2015', 'Nov-2015', 'Jun-2015', 'Jul-2015',
       'May-2015', 'Sep-2014', 'Apr-2015', 'Oct-2014', 'Jan-2015',
       'Mar-2015', 'Feb-2015', 'Nov-2014', 'Aug-2014', 'Dec-2014',
       'Jul-2014', 'Apr-2014', 'Jun-2014', 'Mar-2014', 'May-2014',
       'Feb-2014', 'Jan-2014', 'Nov-2013', 'Oct-2013', 'Dec-2013',
       'Jul-2013', 'Aug-2013', 'Sep-2013', 'Jun-2013', 'Feb-2013',
       'Mar-2013', 'May-2013', 'Nov-2012', 'Dec-2012', 'A

#### Re-read data from "loan.csv" by handling mixed data type in Columns (19,47,55,112,123,124,125,128,129,130,133,139,140,141)

# Note: Run notebook from here

In [1]:
#load python packages
import os
import pandas as pd
import pandas.api.types as ptypes
import datetime
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
df = pd.read_csv("loan.csv", dtype={'desc':object, 'next_pymnt_d':object, 'verification_status_joint':object, 'sec_app_earliest_cr_line':object, 'hardship_type':object, 'hardship_reason':object, 'hardship_status':object, 'hardship_start_date':object, 'hardship_end_date':object, 'payment_plan_start_date':object, 'hardship_loan_status':object, 'debt_settlement_flag_date':object, 'settlement_status':object, 'settlement_date':object})
df.head(5)

id  member_id  loan_amnt  funded_amnt  funded_amnt_inv        term  \
0 NaN        NaN       2500         2500           2500.0   36 months   
1 NaN        NaN      30000        30000          30000.0   60 months   
2 NaN        NaN       5000         5000           5000.0   36 months   
3 NaN        NaN       4000         4000           4000.0   36 months   
4 NaN        NaN      30000        30000          30000.0   60 months   

   int_rate  installment grade sub_grade  ... hardship_payoff_balance_amount  \
0     13.56        84.92     C        C1  ...                            NaN   
1     18.94       777.23     D        D2  ...                            NaN   
2     17.97       180.69     D        D1  ...                            NaN   
3     18.94       146.51     D        D2  ...                            NaN   
4     16.14       731.78     C        C4  ...                            NaN   

  hardship_last_payment_amount disbursement_method  debt_settlement_flag  \
0                          NaN                Cash                     N   
1                          NaN                Cash                     N   
2                          NaN                Cash                     N   
3                          NaN                Cash                     N   
4                          NaN                Cash                     N   

  debt_settlement_flag_date settlement_status settlement_date  \
0                       NaN               NaN             NaN   
1                       NaN               NaN             NaN   
2                       NaN               NaN             NaN   
3                       NaN               NaN             NaN   
4                       NaN               NaN             NaN   

  settlement_amount  settlement_percentage settlement_term  
0               NaN                    NaN             NaN  
1               NaN                    NaN             NaN  
2               NaN                    NaN             NaN  
3               NaN                    NaN             NaN  
4               NaN                    NaN             NaN  

[5 rows x 145 columns]

### Data Definition

#### Check column names

In [3]:
columns = df.columns

In [4]:
columns[:40]

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title',
       'emp_length', 'home_ownership', 'annual_inc', 'verification_status',
       'issue_d', 'loan_status', 'pymnt_plan', 'url', 'desc', 'purpose',
       'title', 'zip_code', 'addr_state', 'dti', 'delinq_2yrs',
       'earliest_cr_line', 'inq_last_6mths', 'mths_since_last_delinq',
       'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'initial_list_status', 'out_prncp',
       'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv'],
      dtype='object')

In [5]:
columns[40:80]

Index(['total_rec_prncp', 'total_rec_int', 'total_rec_late_fee', 'recoveries',
       'collection_recovery_fee', 'last_pymnt_d', 'last_pymnt_amnt',
       'next_pymnt_d', 'last_credit_pull_d', 'collections_12_mths_ex_med',
       'mths_since_last_major_derog', 'policy_code', 'application_type',
       'annual_inc_joint', 'dti_joint', 'verification_status_joint',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt'],
      dtype='object')

In [6]:
columns[80:120]

Index(['mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op',
       'mo_sin_rcnt_tl', 'mort_acc', 'mths_since_recent_bc',
       'mths_since_recent_bc_dlq', 'mths_since_recent_inq',
       'mths_since_recent_revol_delinq', 'num_accts_ever_120_pd',
       'num_actv_bc_tl', 'num_actv_rev_tl', 'num_bc_sats', 'num_bc_tl',
       'num_il_tl', 'num_op_rev_tl', 'num_rev_accts', 'num_rev_tl_bal_gt_0',
       'num_sats', 'num_tl_120dpd_2m', 'num_tl_30dpd', 'num_tl_90g_dpd_24m',
       'num_tl_op_past_12m', 'pct_tl_nvr_dlq', 'percent_bc_gt_75',
       'pub_rec_bankruptcies', 'tax_liens', 'tot_hi_cred_lim',
       'total_bal_ex_mort', 'total_bc_limit', 'total_il_high_credit_limit',
       'revol_bal_joint', 'sec_app_earliest_cr_line', 'sec_app_inq_last_6mths',
       'sec_app_mort_acc', 'sec_app_open_acc', 'sec_app_revol_util',
       'sec_app_open_act_il', 'sec_app_num_rev_accts',
       'sec_app_chargeoff_within_12_mths'],
      dtype='object')

In [7]:
columns[120:]

Index(['sec_app_collections_12_mths_ex_med',
       'sec_app_mths_since_last_major_derog', 'hardship_flag', 'hardship_type',
       'hardship_reason', 'hardship_status', 'deferral_term',
       'hardship_amount', 'hardship_start_date', 'hardship_end_date',
       'payment_plan_start_date', 'hardship_length', 'hardship_dpd',
       'hardship_loan_status', 'orig_projected_additional_accrued_interest',
       'hardship_payoff_balance_amount', 'hardship_last_payment_amount',
       'disbursement_method', 'debt_settlement_flag',
       'debt_settlement_flag_date', 'settlement_status', 'settlement_date',
       'settlement_amount', 'settlement_percentage', 'settlement_term'],
      dtype='object')

All column names look good.

#### Data types

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260668 entries, 0 to 2260667
Columns: 145 entries, id to settlement_term
dtypes: float64(105), int64(4), object(36)
memory usage: 2.4+ GB


In [9]:
df.dtypes

id                       float64
member_id                float64
loan_amnt                  int64
funded_amnt                int64
funded_amnt_inv          float64
                          ...   
settlement_status         object
settlement_date           object
settlement_amount        float64
settlement_percentage    float64
settlement_term          float64
Length: 145, dtype: object

#### Data description

Unique values, Percent of unique values

In [10]:
len(df)

2260668

In [11]:
from pandas.api.types import is_numeric_dtype

column_list = columns.values.tolist()
df_len = len(df)
print("Percentage of unique values for all numeric columns\n")
for column_name in column_list:
    if is_numeric_dtype(df[column_name]):
        print(column_name, df[column_name].unique().size / df_len)

Percentage of unique values for all numeric columns

id 4.4234712925560056e-07
member_id 4.4234712925560056e-07
loan_amnt 0.0006953696871898041
funded_amnt 0.0006953696871898041
funded_amnt_inv 0.004448685078923575
int_rate 0.0002976996179890192
installment 0.04126921777103051
annual_inc 0.03953212059444377
url 4.4234712925560056e-07
dti 0.004797696963906244
delinq_2yrs 1.680919091171282e-05
inq_last_6mths 1.2828066748412415e-05
mths_since_last_delinq 7.69684004904745e-05
mths_since_last_record 5.750512680322807e-05
open_acc 4.069593589151525e-05
pub_rec 1.9463273687246426e-05
revol_bal 0.045230436313514415
revol_util 0.0006329987419647644
total_acc 6.767911077610689e-05
out_prncp 0.1611908515536116
out_prncp_inv 0.16692101626598863
total_pymnt 0.7114145022621632
total_pymnt_inv 0.5746482897975289
total_rec_prncp 0.2156119341716696
total_rec_int 0.27860570415470115
total_rec_late_fee 0.00795826720243751
recoveries 0.056585044774376425
collection_recovery_fee 0.06212721195681984
last_py

Verified that 
id,member_id,url have only one unique value null.  
policy_code has only one value 1.
deferral_term, hardship_length have a lot of missing values.

Checking value_counts for 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int', 'last_pymnt_amnt', 'tot_cur_bal', 'tot_hi_cred_lim'.  Percent of unique values in these numeric column > 0.2.

In [12]:
df['total_pymnt'].value_counts(dropna=False)

0.000000        1008
1215.490000      195
1257.300000      176
11258.436374     167
1246.160000      158
                ... 
14894.884647       1
10406.139186       1
21227.130000       1
2128.678965        1
15228.956199       1
Name: total_pymnt, Length: 1608272, dtype: int64

In [13]:
df['total_pymnt_inv'].value_counts(dropna=False)

0.00        1286
11431.12     266
11784.23     265
11258.44     234
11471.31     218
            ... 
4886.31        1
6199.97        1
30880.54       1
42733.27       1
11658.44       1
Name: total_pymnt_inv, Length: 1299089, dtype: int64

In [14]:
df['total_rec_prncp'].value_counts(dropna=False)

10000.00    78590
12000.00    57687
15000.00    54801
20000.00    53752
5000.00     39524
            ...  
6820.25         1
7233.53         1
14953.95        1
2665.43         1
16168.43        1
Name: total_rec_prncp, Length: 487427, dtype: int64

In [15]:
df['total_rec_int'].value_counts(dropna=False)

0.00        2657
1431.12      316
1784.23      310
1955.40      246
956.78       245
            ... 
11894.31       1
9150.00        1
9150.25        1
4353.91        1
15609.32       1
Name: total_rec_int, Length: 629835, dtype: int64

In [16]:
df['last_pymnt_amnt'].value_counts(dropna=False)

50.00       3082
0.00        2876
100.00      2061
301.15      1967
332.10      1911
            ... 
15769.68       1
1328.35        1
1343.65        1
16441.58       1
16103.18       1
Name: last_pymnt_amnt, Length: 692560, dtype: int64

In [17]:
df['tot_cur_bal'].value_counts(dropna=False)

NaN         70276
0.0           959
14186.0        41
23772.0        39
20275.0        39
            ...  
667152.0        1
438541.0        1
438542.0        1
244760.0        1
548896.0        1
Name: tot_cur_bal, Length: 487689, dtype: int64

In [18]:
df['tot_hi_cred_lim'].value_counts(dropna=False)

NaN         70276
12500.0       716
15000.0       712
15500.0       697
19000.0       696
            ...  
455948.0        1
455953.0        1
455958.0        1
455964.0        1
426543.0        1
Name: tot_hi_cred_lim, Length: 529973, dtype: int64

In [19]:
df['deferral_term'].value_counts(dropna=False)

NaN    2250055
3.0      10613
Name: deferral_term, dtype: int64

In [20]:
df['hardship_length'].value_counts(dropna=False)

NaN    2250055
3.0      10613
Name: hardship_length, dtype: int64

Describe data.

Check for data validity.

In [21]:
data_desc = df.describe()

The description includes all float64 and int64 data.
Dropping id, member_id columns.

In [22]:
data_desc.drop(['id','member_id'], axis=1, inplace=True)

In [23]:
data_desc = data_desc.T

In [24]:
data_desc

count          mean          std     min  \
loan_amnt                       2260668.0  15046.931228  9190.245488  500.00   
funded_amnt                     2260668.0  15041.664057  9188.413022  500.00   
funded_amnt_inv                 2260668.0  15023.437624  9192.331807    0.00   
int_rate                        2260668.0     13.092913     4.832114    5.31   
installment                     2260668.0    445.807646   267.173725    4.93   
...                                   ...           ...          ...     ...   
hardship_payoff_balance_amount    10613.0  11628.036442  7615.161123   55.73   
hardship_last_payment_amount      10613.0    193.606331   198.694368    0.01   
settlement_amount                 33056.0   5030.606922  3692.027842   44.21   
settlement_percentage             33056.0     47.775600     7.336379    0.20   
settlement_term                   33056.0     13.148596     8.192319    0.00   

                                    25%        50%         75%       max  
loan_amnt                       8000.00  12900.000  20000.0000  40000.00  
funded_amnt                     8000.00  12875.000  20000.0000  40000.00  
funded_amnt_inv                 8000.00  12800.000  20000.0000  40000.00  
int_rate                           9.49     12.620     15.9900     30.99  
installment                      251.65    377.990    593.3200   1719.83  
...                                 ...        ...         ...       ...  
hardship_payoff_balance_amount  5628.73  10044.220  16114.9400  40306.41  
hardship_last_payment_amount      43.78    132.890    284.1800   1407.86  
settlement_amount               2227.00   4172.855   6870.7825  33601.00  
settlement_percentage             45.00     45.000     50.0000    521.35  
settlement_term                    6.00     14.000     18.0000    181.00  

[107 rows x 8 columns]

Calculate range.

In [25]:
data_desc['range'] = data_desc['max'] - data_desc['min']
data_desc

count          mean          std     min  \
loan_amnt                       2260668.0  15046.931228  9190.245488  500.00   
funded_amnt                     2260668.0  15041.664057  9188.413022  500.00   
funded_amnt_inv                 2260668.0  15023.437624  9192.331807    0.00   
int_rate                        2260668.0     13.092913     4.832114    5.31   
installment                     2260668.0    445.807646   267.173725    4.93   
...                                   ...           ...          ...     ...   
hardship_payoff_balance_amount    10613.0  11628.036442  7615.161123   55.73   
hardship_last_payment_amount      10613.0    193.606331   198.694368    0.01   
settlement_amount                 33056.0   5030.606922  3692.027842   44.21   
settlement_percentage             33056.0     47.775600     7.336379    0.20   
settlement_term                   33056.0     13.148596     8.192319    0.00   

                                    25%        50%         75%       max  \
loan_amnt                       8000.00  12900.000  20000.0000  40000.00   
funded_amnt                     8000.00  12875.000  20000.0000  40000.00   
funded_amnt_inv                 8000.00  12800.000  20000.0000  40000.00   
int_rate                           9.49     12.620     15.9900     30.99   
installment                      251.65    377.990    593.3200   1719.83   
...                                 ...        ...         ...       ...   
hardship_payoff_balance_amount  5628.73  10044.220  16114.9400  40306.41   
hardship_last_payment_amount      43.78    132.890    284.1800   1407.86   
settlement_amount               2227.00   4172.855   6870.7825  33601.00   
settlement_percentage             45.00     45.000     50.0000    521.35   
settlement_term                    6.00     14.000     18.0000    181.00   

                                   range  
loan_amnt                       39500.00  
funded_amnt                     39500.00  
funded_amnt_inv                 40000.00  
int_rate                           25.68  
installment                      1714.90  
...                                  ...  
hardship_payoff_balance_amount  40250.68  
hardship_last_payment_amount     1407.85  
settlement_amount               33556.79  
settlement_percentage             521.15  
settlement_term                   181.00  

[107 rows x 9 columns]

### Data Cleaning

In [26]:
"""
Dropping the following columns
'id' - Has all null values
'member_id' - Has all null values
'url' - Has all null values
'policy_code' - Has only one value '1' for all observations
'desc' - Text descriptions
'emp_title' - Title of employee
'emp_length' - Employment length
'disbursement method' - Cash or Card
'purpose' - Text describing purpose of loan
'earliest_cr_line' - The month the borrower's earliest credit line was opened
'total_rec_late_fee'
'collection_recovery_fee'
'mths_since_rcnt_il'
'open_il_12m'
'open_il_24m'
'open_rv_12m'
'open_rv_24m'
'total_cu_tl'
'acc_open_past_24mths'
'bc_open_to_buy'
'mo_sin_old_il_acct'
'mo_sin_old_rev_tl_op'
'mo_sin_rcnt_rev_tl_op'
'mo_sin_rcnt_tl'
'mths_since_recent_bc'
'num_actv_bc_tl'
'num_actv_rev_tl'
'num_bc_sats'
'num_bc_tl'
'num_il_tl'
'num_op_rev_tl'
'num_rev_accts'
'num_rev_tl_bal_gt_0'
'num_sats'
'num_tl_op_past_12m'
'open_acc'
'total_acc'
'mort_acc'
'issue_d'
"""

"\nDropping the following columns\n'id' - Has all null values\n'member_id' - Has all null values\n'url' - Has all null values\n'policy_code' - Has only one value '1' for all observations\n'desc' - Text descriptions\n'emp_title' - Title of employee\n'emp_length' - Employment length\n'disbursement method' - Cash or Card\n'purpose' - Text describing purpose of loan\n'earliest_cr_line' - The month the borrower's earliest credit line was opened\n'total_rec_late_fee'\n'collection_recovery_fee'\n'mths_since_rcnt_il'\n'open_il_12m'\n'open_il_24m'\n'open_rv_12m'\n'open_rv_24m'\n'total_cu_tl'\n'acc_open_past_24mths'\n'bc_open_to_buy'\n'mo_sin_old_il_acct'\n'mo_sin_old_rev_tl_op'\n'mo_sin_rcnt_rev_tl_op'\n'mo_sin_rcnt_tl'\n'mths_since_recent_bc'\n'num_actv_bc_tl'\n'num_actv_rev_tl'\n'num_bc_sats'\n'num_bc_tl'\n'num_il_tl'\n'num_op_rev_tl'\n'num_rev_accts'\n'num_rev_tl_bal_gt_0'\n'num_sats'\n'num_tl_op_past_12m'\n'open_acc'\n'total_acc'\n'mort_acc'\n'issue_d'\n"

In [27]:
df.drop(['id','member_id','url','policy_code','desc','emp_title','emp_length','disbursement_method','purpose','earliest_cr_line','total_rec_late_fee','collection_recovery_fee','mths_since_rcnt_il','open_il_12m','open_il_24m','open_rv_12m','open_rv_24m','total_cu_tl','acc_open_past_24mths','bc_open_to_buy','mo_sin_old_il_acct','mo_sin_old_rev_tl_op','mo_sin_rcnt_rev_tl_op','mo_sin_rcnt_tl','mths_since_recent_bc','num_actv_bc_tl','num_actv_rev_tl','num_bc_sats','num_bc_tl','num_il_tl','num_op_rev_tl','num_rev_accts','num_rev_tl_bal_gt_0','num_sats','num_tl_op_past_12m','open_acc','total_acc','mort_acc','issue_d'], axis=1, inplace=True)

In [28]:
df.head()

loan_amnt  funded_amnt  funded_amnt_inv        term  int_rate  installment  \
0       2500         2500           2500.0   36 months     13.56        84.92   
1      30000        30000          30000.0   60 months     18.94       777.23   
2       5000         5000           5000.0   36 months     17.97       180.69   
3       4000         4000           4000.0   36 months     18.94       146.51   
4      30000        30000          30000.0   60 months     16.14       731.78   

  grade sub_grade home_ownership  annual_inc  ...  \
0     C        C1           RENT     55000.0  ...   
1     D        D2       MORTGAGE     90000.0  ...   
2     D        D1       MORTGAGE     59280.0  ...   
3     D        D2       MORTGAGE     92000.0  ...   
4     C        C4       MORTGAGE     57250.0  ...   

  orig_projected_additional_accrued_interest hardship_payoff_balance_amount  \
0                                        NaN                            NaN   
1                                        NaN                            NaN   
2                                        NaN                            NaN   
3                                        NaN                            NaN   
4                                        NaN                            NaN   

  hardship_last_payment_amount debt_settlement_flag debt_settlement_flag_date  \
0                          NaN                    N                       NaN   
1                          NaN                    N                       NaN   
2                          NaN                    N                       NaN   
3                          NaN                    N                       NaN   
4                          NaN                    N                       NaN   

  settlement_status  settlement_date  settlement_amount  \
0               NaN              NaN                NaN   
1               NaN              NaN                NaN   
2               NaN              NaN                NaN   
3               NaN              NaN                NaN   
4               NaN              NaN                NaN   

   settlement_percentage  settlement_term  
0                    NaN              NaN  
1                    NaN              NaN  
2                    NaN              NaN  
3                    NaN              NaN  
4                    NaN              NaN  

[5 rows x 106 columns]

In [29]:
df.shape

(2260668, 106)

#### Handle missing values

In [30]:
# If a column has more than 95% missing values, drop that column
#column_list = df.columns.values.tolist()
#df_len = len(df)
#threshold = round(0.05 * df_len) # 5% non null values
#drop_list = []

#for column_name in column_list:
#    if df[column_name].count() < threshold:
#        drop_list.append(column_name)

In [31]:
#print("Columns having more than 95% missing values\n\n" + str(drop_list) + "\n")

In [32]:
# len(drop_list)

# Note:  There are 31 columns with >95% missing values.  But, many of these columns appear to be related to loan defaults.  Hence, decided to keep all columns.

In [33]:
#df.drop(drop_list, axis=1, inplace=True)

In [34]:
#df.shape

#### Check for duplicate rows

In [35]:
duplicatedRowsDF = df[df.duplicated()]
duplicatedRowsDF

Empty DataFrame
Columns: [loan_amnt, funded_amnt, funded_amnt_inv, term, int_rate, installment, grade, sub_grade, home_ownership, annual_inc, verification_status, loan_status, pymnt_plan, title, zip_code, addr_state, dti, delinq_2yrs, inq_last_6mths, mths_since_last_delinq, mths_since_last_record, pub_rec, revol_bal, revol_util, initial_list_status, out_prncp, out_prncp_inv, total_pymnt, total_pymnt_inv, total_rec_prncp, total_rec_int, recoveries, last_pymnt_d, last_pymnt_amnt, next_pymnt_d, last_credit_pull_d, collections_12_mths_ex_med, mths_since_last_major_derog, application_type, annual_inc_joint, dti_joint, verification_status_joint, acc_now_delinq, tot_coll_amt, tot_cur_bal, open_acc_6m, open_act_il, total_bal_il, il_util, max_bal_bc, all_util, total_rev_hi_lim, inq_fi, inq_last_12m, avg_cur_bal, bc_util, chargeoff_within_12_mths, delinq_amnt, mths_since_recent_bc_dlq, mths_since_recent_inq, mths_since_recent_revol_delinq, num_accts_ever_120_pd, num_tl_120dpd_2m, num_tl_30dpd, num_tl_90g_dpd_24m, pct_tl_nvr_dlq, percent_bc_gt_75, pub_rec_bankruptcies, tax_liens, tot_hi_cred_lim, total_bal_ex_mort, total_bc_limit, total_il_high_credit_limit, revol_bal_joint, sec_app_earliest_cr_line, sec_app_inq_last_6mths, sec_app_mort_acc, sec_app_open_acc, sec_app_revol_util, sec_app_open_act_il, sec_app_num_rev_accts, sec_app_chargeoff_within_12_mths, sec_app_collections_12_mths_ex_med, sec_app_mths_since_last_major_derog, hardship_flag, hardship_type, hardship_reason, hardship_status, deferral_term, hardship_amount, hardship_start_date, hardship_end_date, payment_plan_start_date, hardship_length, hardship_dpd, hardship_loan_status, orig_projected_additional_accrued_interest, hardship_payoff_balance_amount, hardship_last_payment_amount, debt_settlement_flag, ...]
Index: []

[0 rows x 106 columns]

In [36]:
df_desc = df.describe()
df_desc = df_desc.T
df_desc

count          mean          std     min  \
loan_amnt                       2260668.0  15046.931228  9190.245488  500.00   
funded_amnt                     2260668.0  15041.664057  9188.413022  500.00   
funded_amnt_inv                 2260668.0  15023.437624  9192.331807    0.00   
int_rate                        2260668.0     13.092913     4.832114    5.31   
installment                     2260668.0    445.807646   267.173725    4.93   
...                                   ...           ...          ...     ...   
hardship_payoff_balance_amount    10613.0  11628.036442  7615.161123   55.73   
hardship_last_payment_amount      10613.0    193.606331   198.694368    0.01   
settlement_amount                 33056.0   5030.606922  3692.027842   44.21   
settlement_percentage             33056.0     47.775600     7.336379    0.20   
settlement_term                   33056.0     13.148596     8.192319    0.00   

                                    25%        50%         75%       max  
loan_amnt                       8000.00  12900.000  20000.0000  40000.00  
funded_amnt                     8000.00  12875.000  20000.0000  40000.00  
funded_amnt_inv                 8000.00  12800.000  20000.0000  40000.00  
int_rate                           9.49     12.620     15.9900     30.99  
installment                      251.65    377.990    593.3200   1719.83  
...                                 ...        ...         ...       ...  
hardship_payoff_balance_amount  5628.73  10044.220  16114.9400  40306.41  
hardship_last_payment_amount      43.78    132.890    284.1800   1407.86  
settlement_amount               2227.00   4172.855   6870.7825  33601.00  
settlement_percentage             45.00     45.000     50.0000    521.35  
settlement_term                    6.00     14.000     18.0000    181.00  

[77 rows x 8 columns]

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260668 entries, 0 to 2260667
Columns: 106 entries, loan_amnt to settlement_term
dtypes: float64(74), int64(3), object(29)
memory usage: 1.8+ GB


In [38]:
column_list = df.columns.values.tolist()
df_len = len(df)

In [39]:
print("Filling NaNs with 0 for all numeric columns\n")
for column_name in column_list:
    if is_numeric_dtype(df[column_name]):
        df[column_name].fillna(0, inplace=True)

Filling NaNs with 0 for all numeric columns



In [40]:
from pandas.api.types import is_string_dtype

obj_list = []

print("Value counts for object type columns:")
for column_name in column_list:
    if is_string_dtype(df[column_name]):
        obj_list.append(column_name)
        print("Column = " + column_name + ":\n", df[column_name].value_counts(), "\n")
        


Value counts for object type columns:
Column = term:
  36 months    1609754
 60 months     650914
Name: term, dtype: int64 

Column = grade:
 B    663557
C    650053
A    433027
D    324424
E    135639
F     41800
G     12168
Name: grade, dtype: int64 

Column = sub_grade:
 C1    145903
B5    140288
B4    139793
B3    131514
C2    131116
C3    129193
C4    127115
B2    126621
B1    125341
C5    116726
A5    107617
A4     95874
A1     86790
D1     81787
A3     73184
D2     72899
A2     69562
D3     64819
D4     56896
D5     48023
E1     33573
E2     29924
E3     26708
E4     22763
E5     22671
F1     13413
F2      9305
F3      7791
F4      6124
F5      5167
G1      4106
G2      2688
G3      2094
G4      1712
G5      1568
Name: sub_grade, dtype: int64 

Column = home_ownership:
 MORTGAGE    1111450
RENT         894929
OWN          253057
ANY             996
OTHER           182
NONE             54
Name: home_ownership, dtype: int64 

Column = verification_status:
 Source Verified    88623

In [41]:
print("Dropping last_pymnt_d, next_pymnt_d, last_credit_pull_d, sec_app_earliest_cr_line, hardship_start_date, hardship_end_date, payment_plan_start_date, debt_settlement_flag_date, settlement_date")
df.drop(['last_pymnt_d','next_pymnt_d','last_credit_pull_d','sec_app_earliest_cr_line','hardship_start_date','hardship_end_date','payment_plan_start_date','debt_settlement_flag_date','settlement_date'], axis=1, inplace=True)

Dropping last_pymnt_d, next_pymnt_d, last_credit_pull_d, sec_app_earliest_cr_line, hardship_start_date, hardship_end_date, payment_plan_start_date, debt_settlement_flag_date, settlement_date


In [42]:
df.shape

(2260668, 97)

In [43]:
df.to_csv("data\Cap2_step2_output.csv")